/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#035300",
        "surface": "#f7f9ff",
        "on-secondary-fixed-variant": "#6d3a00",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-bright": "#f7f9ff",
        "inverse-surface": "#2d3135",
        "on-tertiary-container": "#309d22",
        "on-secondary-fixed": "#2e1500",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#000e00",
        "surface-container": "#ebeef3",
        "on-tertiary-fixed": "#012200",
        "on-surface-variant": "#44474e",
        "surface-variant": "#e0e3e8",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "tertiary-container": "#012800",
        "tertiary-fixed-dim": "#72de5c",
        "on-background": "#181c20",
        "secondary-container": "#fe9832",
        "on-error": "#ffffff",
        "on-primary-container": "#708ab5",
        "surface-tint": "#465f88",
        "surface-container-low": "#f1f4f9",
        "outline": "#74777f",
        "secondary-fixed": "#ffdcc2",
        "primary-fixed-dim": "#aec7f6",
        "surface-dim": "#d7dadf",
        "primary": "#000a1e",
        "on-surface": "#181c20",
        "inverse-primary": "#aec7f6",
        "surface-container-high": "#e5e8ee",
        "on-primary-fixed-variant": "#2d476f",
        "on-primary-fixed": "#001b3d",
        "secondary-fixed-dim": "#ffb77a",
        "primary-container": "#002147",
        "outline-variant": "#c4c6cf",
        "error": "#ba1a1a",
        "tertiary-fixed": "#8dfc75",
        "inverse-on-surface": "#eef1f6",
        "secondary": "#8f4e00",
        "surface-container-highest": "#e0e3e8",
        "background": "#f7f9ff",
        "primary-fixed": "#d6e3ff",
        "on-secondary-container": "#683700",
        // Additional Civic specific tokens
        "gov-saffron": "#FF9933",
        "gov-green": "#138808",
        "gov-navy": "#002147",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        gutter: "24px",
        "container-max": "1280px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        sans: ["'Public Sans'", "system-ui", "sans-serif"],
        "display-lg": ["'Public Sans'", "sans-serif"],
        "headline-lg": ["'Public Sans'", "sans-serif"],
        "headline-md": ["'Public Sans'", "sans-serif"],
        "headline-sm": ["'Public Sans'", "sans-serif"],
        "body-lg": ["'Public Sans'", "sans-serif"],
        "body-md": ["'Public Sans'", "sans-serif"],
        "body-sm": ["'Public Sans'", "sans-serif"],
        "label-md": ["'Public Sans'", "sans-serif"],
        "label-sm": ["'Public Sans'", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      boxShadow: {
        ambient: "0px 2px 4px rgba(0, 0, 0, 0.05)",
        card: "0px 2px 8px rgba(0, 0, 0, 0.08)",
        elevation: "0px 4px 16px rgba(0, 33, 71, 0.12)",
      },
    },
  },
  plugins: [],
};
